services:
  rdb:
    image: postgres:16
    container_name: rdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rapp
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - rdb
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: